# Generated by Django 4.2.13 on 2024-06-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupMember',
        ),
    ]
