# Generated by Django 4.2.13 on 2024-06-26 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_groupmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('T', 'Team Lead'), ('M', 'Manager')], default='M', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='accounts.group')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_workers', to='accounts.worker')),
            ],
        ),
    ]
